version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - WAZUH_API_URL=https://10.144.90.95:55000
      - WAZUH_API_USER=${WAZUH_API_USER}
      - WAZUH_API_PASSWORD=${WAZUH_API_PASSWORD}
      - WAZUH_VERIFY_SSL=False
      - OPENSEARCH_URL=https://10.144.90.95:9200
      - OPENSEARCH_USER=${OPENSEARCH_USER}
      - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
      - OPENSEARCH_VERIFY_SSL=False
      - OPENSEARCH_INDEX_PATTERN=wazuh-alerts-*
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_USE_TLS=True
      - SMTP_SENDER_NAME=WAZUH Alerts
      - FLASK_DEBUG=False
      - SESSION_SECRET=${SESSION_SECRET}
      - TZ=UTC
    volumes:
      - ./instance:/app/instance
      - ./logs:/app/logs

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-azsentinel}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-azsentinel123}
      - POSTGRES_DB=${POSTGRES_DB:-azsentinel}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: